---
default_language_version:
  # force all unspecified python hooks to run python3
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-xml
      - id: debug-statements
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: files/(issue|motd)
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: pretty-format-json
        args:
          - --autofix
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  # Text file hooks
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.36.0
    hooks:
      - id: markdownlint
        args:
          - --config=.mdl_config.yaml
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.32.0
    hooks:
      - id: yamllint
        args:
          - --strict

  # GitHub Actions hooks
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.26.3
    hooks:
      - id: check-github-actions
      - id: check-github-workflows

  # pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit
    # pre-commit v3+ dropped support for Python <3.8. Until this project and
    # the build.yml workflow can migrate to Python 3.8 or newer we must
    # continue to use an older version.
    rev: v2.21.0
    hooks:
      - id: validate_manifest

  # Go hooks
  - repo: https://github.com/TekWizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      # Style Checkers
      - id: go-critic
      # StaticCheck
      - id: go-staticcheck-repo-mod
      # Go Build
      - id: go-build-repo-mod
      # Go Mod Tidy
      - id: go-mod-tidy-repo
      # Go Test
      - id: go-test-repo-mod
      # Go Vet
      - id: go-vet-repo-mod
      # GoSec
      - id: go-sec-repo-mod

  # Nix hooks
  - repo: https://github.com/nix-community/nixpkgs-fmt
    rev: v1.3.0
    hooks:
      - id: nixpkgs-fmt

  # Shell script hooks
  - repo: https://github.com/cisagov/pre-commit-shfmt
    rev: v0.0.2
    hooks:
      - id: shfmt
        args:
          # Indent by two spaces
          - -i
          - '2'
          # Binary operators may start a line
          - -bn
          # Switch cases are indented
          - -ci
          # Redirect operators are followed by a space
          - -sr
  - repo: https://github.com/detailyang/pre-commit-shell
    rev: 1.0.5
    hooks:
      - id: shell-lint

  # Python hooks
  # Run bandit on the "tests" tree with a configuration
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        name: bandit (tests tree)
        files: tests
        args:
          - --config=.bandit.yml
        additional_dependencies:
          - importlib-metadata<5
  # Run bandit on everything except the "tests" tree
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        name: bandit (everything else)
        exclude: tests
        additional_dependencies:
          - importlib-metadata<5
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.9.1
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    # flake8 v6+ dropped support for Python <3.8. Until this project and
    # the build.yml workflow can migrate to Python 3.8 or newer we must
    # continue to use an older version.
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-docstrings
  - repo: https://github.com/PyCQA/isort
    # isort 5.12.0 dropped support for Python <3.8. Until this project and
    # the build.yml workflow can migrate to Python 3.8 or newer we must
    # continue to use an older version.
    rev: 5.11.5
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        additional_dependencies:
          - pytest
          - pytablewriter
          - types-docopt
          - types-pyOpenSSL
          - types-requests
          - types-setuptools
          - types-urllib3
        # Override the default arguments to drop the --ignore-missing-imports
        # option to enforce a complete mypy configuration.
        args:
          - --scripts-are-modules
  - repo: https://github.com/asottile/pyupgrade
    # pyupgrade no longer supports Python 3.7 as of version 3.4.0, so
    # we cannot upgrade past the 3.3.2 release:
    # https://github.com/asottile/pyupgrade/blob/v3.4.0/setup.cfg#L23
    rev: v3.3.2
    hooks:
      - id: pyupgrade

  # Ansible hooks
  # - repo: https://github.com/ansible-community/ansible-lint
  #   # ansible-lint no longer supports Python 3.7 as of version 6.0, so
  #   # we cannot upgrade past the 5.4.0 release:
  #   # https://github.com/ansible/ansible-lint/releases/tag/v6.0.0
  #   #
  #   # But the 5.4.0 release causes a different failure because the
  #   # version of ansible isn't correctly pinned.  The best way forward
  #   # is to simply comment out this pre-commit hook until we can move
  #   # to Python >3.7.
  #   rev: v6.17.0
  #   hooks:
  #     - id: ansible-lint
  #     # files: molecule/default/playbook.yml

  # Terraform hooks
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.2
    hooks:
      - id: terraform_fmt
      - id: terraform_validate

  # Docker hooks
  - repo: https://github.com/IamTheFij/docker-pre-commit
    rev: v3.0.1
    hooks:
      - id: docker-compose-check

  # Packer hooks
  - repo: https://github.com/cisagov/pre-commit-packer
    rev: v0.0.2
    hooks:
      - id: packer_validate
      - id: packer_fmt
